/* 
 * Muhimbi PDF
 *
 * Convert, Merge, Watermark, Secure and OCR files.
 *
 * OpenAPI spec version: 9.16
 * Contact: support@muhimbi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Muhimbi.PDF.Online.Client.Model
{
    /// <summary>
    /// Parameters for Convert Infopath operation
    /// </summary>
    [DataContract]
    public partial class ConvertInfopathData :  IEquatable<ConvertInfopathData>, IValidatableObject
    {
        /// <summary>
        /// Output format
        /// </summary>
        /// <value>Output format</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OutputFormatEnum
        {
            
            /// <summary>
            /// Enum PDF for "PDF"
            /// </summary>
            [EnumMember(Value = "PDF")]
            PDF,
            
            /// <summary>
            /// Enum XPS for "XPS"
            /// </summary>
            [EnumMember(Value = "XPS")]
            XPS,
            
            /// <summary>
            /// Enum DOCX for "DOCX"
            /// </summary>
            [EnumMember(Value = "DOCX")]
            DOCX,
            
            /// <summary>
            /// Enum DOC for "DOC"
            /// </summary>
            [EnumMember(Value = "DOC")]
            DOC,
            
            /// <summary>
            /// Enum ODT for "ODT"
            /// </summary>
            [EnumMember(Value = "ODT")]
            ODT,
            
            /// <summary>
            /// Enum RTF for "RTF"
            /// </summary>
            [EnumMember(Value = "RTF")]
            RTF,
            
            /// <summary>
            /// Enum TXT for "TXT"
            /// </summary>
            [EnumMember(Value = "TXT")]
            TXT,
            
            /// <summary>
            /// Enum MHT for "MHT"
            /// </summary>
            [EnumMember(Value = "MHT")]
            MHT,
            
            /// <summary>
            /// Enum HTML for "HTML"
            /// </summary>
            [EnumMember(Value = "HTML")]
            HTML,
            
            /// <summary>
            /// Enum XML for "XML"
            /// </summary>
            [EnumMember(Value = "XML")]
            XML,
            
            /// <summary>
            /// Enum XLS for "XLS"
            /// </summary>
            [EnumMember(Value = "XLS")]
            XLS,
            
            /// <summary>
            /// Enum XLSX for "XLSX"
            /// </summary>
            [EnumMember(Value = "XLSX")]
            XLSX,
            
            /// <summary>
            /// Enum CSV for "CSV"
            /// </summary>
            [EnumMember(Value = "CSV")]
            CSV,
            
            /// <summary>
            /// Enum ODS for "ODS"
            /// </summary>
            [EnumMember(Value = "ODS")]
            ODS
        }

        /// <summary>
        /// What to do with attachments
        /// </summary>
        /// <value>What to do with attachments</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AttachmentMergeModeEnum
        {
            
            /// <summary>
            /// Enum Default for "Default"
            /// </summary>
            [EnumMember(Value = "Default")]
            Default,
            
            /// <summary>
            /// Enum Merge for "Merge"
            /// </summary>
            [EnumMember(Value = "Merge")]
            Merge,
            
            /// <summary>
            /// Enum AttachAsPDF for "AttachAsPDF"
            /// </summary>
            [EnumMember(Value = "AttachAsPDF")]
            AttachAsPDF,
            
            /// <summary>
            /// Enum AttachOriginal for "AttachOriginal"
            /// </summary>
            [EnumMember(Value = "AttachOriginal")]
            AttachOriginal
        }

        /// <summary>
        /// What to do with attachments which cannot be converted into PDF
        /// </summary>
        /// <value>What to do with attachments which cannot be converted into PDF</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum UnsupportedAttachmentBehaviourEnum
        {
            
            /// <summary>
            /// Enum Error for "Error"
            /// </summary>
            [EnumMember(Value = "Error")]
            Error,
            
            /// <summary>
            /// Enum Remove for "Remove"
            /// </summary>
            [EnumMember(Value = "Remove")]
            Remove,
            
            /// <summary>
            /// Enum AttachOriginal for "AttachOriginal"
            /// </summary>
            [EnumMember(Value = "AttachOriginal")]
            AttachOriginal
        }

        /// <summary>
        /// Specify paper size to be used when it is not specified in the view
        /// </summary>
        /// <value>Specify paper size to be used when it is not specified in the view</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DefaultPaperSizeEnum
        {
            
            /// <summary>
            /// Enum A3 for "A3"
            /// </summary>
            [EnumMember(Value = "A3")]
            A3,
            
            /// <summary>
            /// Enum A4 for "A4"
            /// </summary>
            [EnumMember(Value = "A4")]
            A4,
            
            /// <summary>
            /// Enum A5 for "A5"
            /// </summary>
            [EnumMember(Value = "A5")]
            A5,
            
            /// <summary>
            /// Enum Legal for "Legal"
            /// </summary>
            [EnumMember(Value = "Legal")]
            Legal,
            
            /// <summary>
            /// Enum Letter for "Letter"
            /// </summary>
            [EnumMember(Value = "Letter")]
            Letter,
            
            /// <summary>
            /// Enum Custom for "Custom"
            /// </summary>
            [EnumMember(Value = "Custom")]
            Custom
        }

        /// <summary>
        /// Force this papers size regardless of whether it is set in the views or not
        /// </summary>
        /// <value>Force this papers size regardless of whether it is set in the views or not</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ForcePaperSizeEnum
        {
            
            /// <summary>
            /// Enum A3 for "A3"
            /// </summary>
            [EnumMember(Value = "A3")]
            A3,
            
            /// <summary>
            /// Enum A4 for "A4"
            /// </summary>
            [EnumMember(Value = "A4")]
            A4,
            
            /// <summary>
            /// Enum A5 for "A5"
            /// </summary>
            [EnumMember(Value = "A5")]
            A5,
            
            /// <summary>
            /// Enum Legal for "Legal"
            /// </summary>
            [EnumMember(Value = "Legal")]
            Legal,
            
            /// <summary>
            /// Enum Letter for "Letter"
            /// </summary>
            [EnumMember(Value = "Letter")]
            Letter,
            
            /// <summary>
            /// Enum Custom for "Custom"
            /// </summary>
            [EnumMember(Value = "Custom")]
            Custom
        }

        /// <summary>
        /// Specify papers size to be used if it is not specified in the view
        /// </summary>
        /// <value>Specify papers size to be used if it is not specified in the view</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DefaultPageOrientationEnum
        {
            
            /// <summary>
            /// Enum Default for "Default"
            /// </summary>
            [EnumMember(Value = "Default")]
            Default,
            
            /// <summary>
            /// Enum Portrait for "Portrait"
            /// </summary>
            [EnumMember(Value = "Portrait")]
            Portrait,
            
            /// <summary>
            /// Enum Landscape for "Landscape"
            /// </summary>
            [EnumMember(Value = "Landscape")]
            Landscape,
            
            /// <summary>
            /// Enum Both for "Both"
            /// </summary>
            [EnumMember(Value = "Both")]
            Both
        }

        /// <summary>
        /// Force page orientation regardless of whether it is set in the view or not
        /// </summary>
        /// <value>Force page orientation regardless of whether it is set in the view or not</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ForcePageOrientationEnum
        {
            
            /// <summary>
            /// Enum Default for "Default"
            /// </summary>
            [EnumMember(Value = "Default")]
            Default,
            
            /// <summary>
            /// Enum Portrait for "Portrait"
            /// </summary>
            [EnumMember(Value = "Portrait")]
            Portrait,
            
            /// <summary>
            /// Enum Landscape for "Landscape"
            /// </summary>
            [EnumMember(Value = "Landscape")]
            Landscape,
            
            /// <summary>
            /// Enum Both for "Both"
            /// </summary>
            [EnumMember(Value = "Both")]
            Both
        }

        /// <summary>
        /// Quality of the output file
        /// </summary>
        /// <value>Quality of the output file</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum QualityEnum
        {
            
            /// <summary>
            /// Enum OptimizeForPrint for "OptimizeForPrint"
            /// </summary>
            [EnumMember(Value = "OptimizeForPrint")]
            OptimizeForPrint,
            
            /// <summary>
            /// Enum OptimizeForOnScreen for "OptimizeForOnScreen"
            /// </summary>
            [EnumMember(Value = "OptimizeForOnScreen")]
            OptimizeForOnScreen,
            
            /// <summary>
            /// Enum Original for "Original"
            /// </summary>
            [EnumMember(Value = "Original")]
            Original
        }

        /// <summary>
        /// Output format
        /// </summary>
        /// <value>Output format</value>
        [DataMember(Name="output_format", EmitDefaultValue=false)]
        public OutputFormatEnum? OutputFormat { get; set; }
        /// <summary>
        /// What to do with attachments
        /// </summary>
        /// <value>What to do with attachments</value>
        [DataMember(Name="attachment_merge_mode", EmitDefaultValue=false)]
        public AttachmentMergeModeEnum? AttachmentMergeMode { get; set; }
        /// <summary>
        /// What to do with attachments which cannot be converted into PDF
        /// </summary>
        /// <value>What to do with attachments which cannot be converted into PDF</value>
        [DataMember(Name="unsupported_attachment_behaviour", EmitDefaultValue=false)]
        public UnsupportedAttachmentBehaviourEnum? UnsupportedAttachmentBehaviour { get; set; }
        /// <summary>
        /// Specify paper size to be used when it is not specified in the view
        /// </summary>
        /// <value>Specify paper size to be used when it is not specified in the view</value>
        [DataMember(Name="default_paper_size", EmitDefaultValue=false)]
        public DefaultPaperSizeEnum? DefaultPaperSize { get; set; }
        /// <summary>
        /// Force this papers size regardless of whether it is set in the views or not
        /// </summary>
        /// <value>Force this papers size regardless of whether it is set in the views or not</value>
        [DataMember(Name="force_paper_size", EmitDefaultValue=false)]
        public ForcePaperSizeEnum? ForcePaperSize { get; set; }
        /// <summary>
        /// Specify papers size to be used if it is not specified in the view
        /// </summary>
        /// <value>Specify papers size to be used if it is not specified in the view</value>
        [DataMember(Name="default_page_orientation", EmitDefaultValue=false)]
        public DefaultPageOrientationEnum? DefaultPageOrientation { get; set; }
        /// <summary>
        /// Force page orientation regardless of whether it is set in the view or not
        /// </summary>
        /// <value>Force page orientation regardless of whether it is set in the view or not</value>
        [DataMember(Name="force_page_orientation", EmitDefaultValue=false)]
        public ForcePageOrientationEnum? ForcePageOrientation { get; set; }
        /// <summary>
        /// Quality of the output file
        /// </summary>
        /// <value>Quality of the output file</value>
        [DataMember(Name="quality", EmitDefaultValue=false)]
        public QualityEnum? Quality { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConvertInfopathData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConvertInfopathData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConvertInfopathData" /> class.
        /// </summary>
        /// <param name="UseAsyncPattern">Use async behaviour for API request (required) (default to false).</param>
        /// <param name="SourceFileName">Name of the source file including extension (required).</param>
        /// <param name="SharepointFile">SharepointFile.</param>
        /// <param name="SourceFileContent">Content of the file to convert (required).</param>
        /// <param name="OutputFormat">Output format (required) (default to OutputFormatEnum.PDF).</param>
        /// <param name="CopyMetadata">Copy metadata (Only for SharePoint operations) (required) (default to false).</param>
        /// <param name="TemplateFileContent">Optional XSN file content.</param>
        /// <param name="ViewsToConvert">Comma separated list view names to convert.</param>
        /// <param name="ConvertAttachments">Include attachments (default to true).</param>
        /// <param name="AttachmentMergeMode">What to do with attachments.</param>
        /// <param name="UnsupportedAttachmentBehaviour">What to do with attachments which cannot be converted into PDF.</param>
        /// <param name="BreakMergeOnError">Break conversion when processing of an individual part fails.</param>
        /// <param name="IncludeAttachmentTypes">Comma separated values, e.g. *.txt, June???.docx.</param>
        /// <param name="ExcludeAttachmentTypes">Comma separated values, e.g. *.txt, June???.docx.</param>
        /// <param name="DefaultPaperSize">Specify paper size to be used when it is not specified in the view.</param>
        /// <param name="DefaultPaperSizeCustom">Applicable if &#39;Default paper size&#39; is set to &#39;Custom&#39;.</param>
        /// <param name="ForcePaperSize">Force this papers size regardless of whether it is set in the views or not.</param>
        /// <param name="ForcePaperSizeCustom">Applicable if &#39;Force paper size&#39; is set to custom.</param>
        /// <param name="DefaultPageOrientation">Specify papers size to be used if it is not specified in the view (default to DefaultPageOrientationEnum.Default).</param>
        /// <param name="ForcePageOrientation">Force page orientation regardless of whether it is set in the view or not.</param>
        /// <param name="StartPage">The first page to include.</param>
        /// <param name="EndPage">The last page to include.</param>
        /// <param name="Quality">Quality of the output file.</param>
        /// <param name="OverrideSettings">Optional settings using Muhimbi&#39;s XML syntax.</param>
        /// <param name="FailOnError">Fail on error (default to true).</param>
        public ConvertInfopathData(bool? UseAsyncPattern = false, string SourceFileName = default(string), SharepointFile SharepointFile = default(SharepointFile), byte[] SourceFileContent = default(byte[]), OutputFormatEnum? OutputFormat = OutputFormatEnum.PDF, bool? CopyMetadata = false, byte[] TemplateFileContent = default(byte[]), string ViewsToConvert = default(string), bool? ConvertAttachments = true, AttachmentMergeModeEnum? AttachmentMergeMode = default(AttachmentMergeModeEnum?), UnsupportedAttachmentBehaviourEnum? UnsupportedAttachmentBehaviour = default(UnsupportedAttachmentBehaviourEnum?), bool? BreakMergeOnError = default(bool?), string IncludeAttachmentTypes = default(string), string ExcludeAttachmentTypes = default(string), DefaultPaperSizeEnum? DefaultPaperSize = default(DefaultPaperSizeEnum?), string DefaultPaperSizeCustom = default(string), ForcePaperSizeEnum? ForcePaperSize = default(ForcePaperSizeEnum?), string ForcePaperSizeCustom = default(string), DefaultPageOrientationEnum? DefaultPageOrientation = DefaultPageOrientationEnum.Default, ForcePageOrientationEnum? ForcePageOrientation = default(ForcePageOrientationEnum?), int? StartPage = default(int?), int? EndPage = default(int?), QualityEnum? Quality = default(QualityEnum?), string OverrideSettings = default(string), bool? FailOnError = true)
        {
            // to ensure "UseAsyncPattern" is required (not null)
            if (UseAsyncPattern == null)
            {
                throw new InvalidDataException("UseAsyncPattern is a required property for ConvertInfopathData and cannot be null");
            }
            else
            {
                this.UseAsyncPattern = UseAsyncPattern;
            }
            // to ensure "SourceFileName" is required (not null)
            if (SourceFileName == null)
            {
                throw new InvalidDataException("SourceFileName is a required property for ConvertInfopathData and cannot be null");
            }
            else
            {
                this.SourceFileName = SourceFileName;
            }
            // to ensure "SourceFileContent" is required (not null)
            if (SourceFileContent == null)
            {
                throw new InvalidDataException("SourceFileContent is a required property for ConvertInfopathData and cannot be null");
            }
            else
            {
                this.SourceFileContent = SourceFileContent;
            }
            // to ensure "OutputFormat" is required (not null)
            if (OutputFormat == null)
            {
                throw new InvalidDataException("OutputFormat is a required property for ConvertInfopathData and cannot be null");
            }
            else
            {
                this.OutputFormat = OutputFormat;
            }
            // to ensure "CopyMetadata" is required (not null)
            if (CopyMetadata == null)
            {
                throw new InvalidDataException("CopyMetadata is a required property for ConvertInfopathData and cannot be null");
            }
            else
            {
                this.CopyMetadata = CopyMetadata;
            }
            this.SharepointFile = SharepointFile;
            this.TemplateFileContent = TemplateFileContent;
            this.ViewsToConvert = ViewsToConvert;
            // use default value if no "ConvertAttachments" provided
            if (ConvertAttachments == null)
            {
                this.ConvertAttachments = true;
            }
            else
            {
                this.ConvertAttachments = ConvertAttachments;
            }
            this.AttachmentMergeMode = AttachmentMergeMode;
            this.UnsupportedAttachmentBehaviour = UnsupportedAttachmentBehaviour;
            this.BreakMergeOnError = BreakMergeOnError;
            this.IncludeAttachmentTypes = IncludeAttachmentTypes;
            this.ExcludeAttachmentTypes = ExcludeAttachmentTypes;
            this.DefaultPaperSize = DefaultPaperSize;
            this.DefaultPaperSizeCustom = DefaultPaperSizeCustom;
            this.ForcePaperSize = ForcePaperSize;
            this.ForcePaperSizeCustom = ForcePaperSizeCustom;
            // use default value if no "DefaultPageOrientation" provided
            if (DefaultPageOrientation == null)
            {
                this.DefaultPageOrientation = DefaultPageOrientationEnum.Default;
            }
            else
            {
                this.DefaultPageOrientation = DefaultPageOrientation;
            }
            this.ForcePageOrientation = ForcePageOrientation;
            this.StartPage = StartPage;
            this.EndPage = EndPage;
            this.Quality = Quality;
            this.OverrideSettings = OverrideSettings;
            // use default value if no "FailOnError" provided
            if (FailOnError == null)
            {
                this.FailOnError = true;
            }
            else
            {
                this.FailOnError = FailOnError;
            }
        }
        
        /// <summary>
        /// Use async behaviour for API request
        /// </summary>
        /// <value>Use async behaviour for API request</value>
        [DataMember(Name="use_async_pattern", EmitDefaultValue=false)]
        public bool? UseAsyncPattern { get; set; }
        /// <summary>
        /// Name of the source file including extension
        /// </summary>
        /// <value>Name of the source file including extension</value>
        [DataMember(Name="source_file_name", EmitDefaultValue=false)]
        public string SourceFileName { get; set; }
        /// <summary>
        /// Gets or Sets SharepointFile
        /// </summary>
        [DataMember(Name="sharepoint_file", EmitDefaultValue=false)]
        public SharepointFile SharepointFile { get; set; }
        /// <summary>
        /// Content of the file to convert
        /// </summary>
        /// <value>Content of the file to convert</value>
        [DataMember(Name="source_file_content", EmitDefaultValue=false)]
        public byte[] SourceFileContent { get; set; }
        /// <summary>
        /// Copy metadata (Only for SharePoint operations)
        /// </summary>
        /// <value>Copy metadata (Only for SharePoint operations)</value>
        [DataMember(Name="copy_metadata", EmitDefaultValue=false)]
        public bool? CopyMetadata { get; set; }
        /// <summary>
        /// Optional XSN file content
        /// </summary>
        /// <value>Optional XSN file content</value>
        [DataMember(Name="template_file_content", EmitDefaultValue=false)]
        public byte[] TemplateFileContent { get; set; }
        /// <summary>
        /// Comma separated list view names to convert
        /// </summary>
        /// <value>Comma separated list view names to convert</value>
        [DataMember(Name="views_to_convert", EmitDefaultValue=false)]
        public string ViewsToConvert { get; set; }
        /// <summary>
        /// Include attachments
        /// </summary>
        /// <value>Include attachments</value>
        [DataMember(Name="convert_attachments", EmitDefaultValue=false)]
        public bool? ConvertAttachments { get; set; }
        /// <summary>
        /// Break conversion when processing of an individual part fails
        /// </summary>
        /// <value>Break conversion when processing of an individual part fails</value>
        [DataMember(Name="break_merge_on_error", EmitDefaultValue=false)]
        public bool? BreakMergeOnError { get; set; }
        /// <summary>
        /// Comma separated values, e.g. *.txt, June???.docx
        /// </summary>
        /// <value>Comma separated values, e.g. *.txt, June???.docx</value>
        [DataMember(Name="include_attachment_types", EmitDefaultValue=false)]
        public string IncludeAttachmentTypes { get; set; }
        /// <summary>
        /// Comma separated values, e.g. *.txt, June???.docx
        /// </summary>
        /// <value>Comma separated values, e.g. *.txt, June???.docx</value>
        [DataMember(Name="exclude_attachment_types", EmitDefaultValue=false)]
        public string ExcludeAttachmentTypes { get; set; }
        /// <summary>
        /// Applicable if &#39;Default paper size&#39; is set to &#39;Custom&#39;
        /// </summary>
        /// <value>Applicable if &#39;Default paper size&#39; is set to &#39;Custom&#39;</value>
        [DataMember(Name="default_paper_size_custom", EmitDefaultValue=false)]
        public string DefaultPaperSizeCustom { get; set; }
        /// <summary>
        /// Applicable if &#39;Force paper size&#39; is set to custom
        /// </summary>
        /// <value>Applicable if &#39;Force paper size&#39; is set to custom</value>
        [DataMember(Name="force_paper_size_custom", EmitDefaultValue=false)]
        public string ForcePaperSizeCustom { get; set; }
        /// <summary>
        /// The first page to include
        /// </summary>
        /// <value>The first page to include</value>
        [DataMember(Name="start_page", EmitDefaultValue=false)]
        public int? StartPage { get; set; }
        /// <summary>
        /// The last page to include
        /// </summary>
        /// <value>The last page to include</value>
        [DataMember(Name="end_page", EmitDefaultValue=false)]
        public int? EndPage { get; set; }
        /// <summary>
        /// Optional settings using Muhimbi&#39;s XML syntax
        /// </summary>
        /// <value>Optional settings using Muhimbi&#39;s XML syntax</value>
        [DataMember(Name="override_settings", EmitDefaultValue=false)]
        public string OverrideSettings { get; set; }
        /// <summary>
        /// Fail on error
        /// </summary>
        /// <value>Fail on error</value>
        [DataMember(Name="fail_on_error", EmitDefaultValue=false)]
        public bool? FailOnError { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConvertInfopathData {\n");
            sb.Append("  UseAsyncPattern: ").Append(UseAsyncPattern).Append("\n");
            sb.Append("  SourceFileName: ").Append(SourceFileName).Append("\n");
            sb.Append("  SharepointFile: ").Append(SharepointFile).Append("\n");
            sb.Append("  SourceFileContent: ").Append(SourceFileContent).Append("\n");
            sb.Append("  OutputFormat: ").Append(OutputFormat).Append("\n");
            sb.Append("  CopyMetadata: ").Append(CopyMetadata).Append("\n");
            sb.Append("  TemplateFileContent: ").Append(TemplateFileContent).Append("\n");
            sb.Append("  ViewsToConvert: ").Append(ViewsToConvert).Append("\n");
            sb.Append("  ConvertAttachments: ").Append(ConvertAttachments).Append("\n");
            sb.Append("  AttachmentMergeMode: ").Append(AttachmentMergeMode).Append("\n");
            sb.Append("  UnsupportedAttachmentBehaviour: ").Append(UnsupportedAttachmentBehaviour).Append("\n");
            sb.Append("  BreakMergeOnError: ").Append(BreakMergeOnError).Append("\n");
            sb.Append("  IncludeAttachmentTypes: ").Append(IncludeAttachmentTypes).Append("\n");
            sb.Append("  ExcludeAttachmentTypes: ").Append(ExcludeAttachmentTypes).Append("\n");
            sb.Append("  DefaultPaperSize: ").Append(DefaultPaperSize).Append("\n");
            sb.Append("  DefaultPaperSizeCustom: ").Append(DefaultPaperSizeCustom).Append("\n");
            sb.Append("  ForcePaperSize: ").Append(ForcePaperSize).Append("\n");
            sb.Append("  ForcePaperSizeCustom: ").Append(ForcePaperSizeCustom).Append("\n");
            sb.Append("  DefaultPageOrientation: ").Append(DefaultPageOrientation).Append("\n");
            sb.Append("  ForcePageOrientation: ").Append(ForcePageOrientation).Append("\n");
            sb.Append("  StartPage: ").Append(StartPage).Append("\n");
            sb.Append("  EndPage: ").Append(EndPage).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  OverrideSettings: ").Append(OverrideSettings).Append("\n");
            sb.Append("  FailOnError: ").Append(FailOnError).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ConvertInfopathData);
        }

        /// <summary>
        /// Returns true if ConvertInfopathData instances are equal
        /// </summary>
        /// <param name="other">Instance of ConvertInfopathData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConvertInfopathData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.UseAsyncPattern == other.UseAsyncPattern ||
                    this.UseAsyncPattern != null &&
                    this.UseAsyncPattern.Equals(other.UseAsyncPattern)
                ) && 
                (
                    this.SourceFileName == other.SourceFileName ||
                    this.SourceFileName != null &&
                    this.SourceFileName.Equals(other.SourceFileName)
                ) && 
                (
                    this.SharepointFile == other.SharepointFile ||
                    this.SharepointFile != null &&
                    this.SharepointFile.Equals(other.SharepointFile)
                ) && 
                (
                    this.SourceFileContent == other.SourceFileContent ||
                    this.SourceFileContent != null &&
                    this.SourceFileContent.Equals(other.SourceFileContent)
                ) && 
                (
                    this.OutputFormat == other.OutputFormat ||
                    this.OutputFormat != null &&
                    this.OutputFormat.Equals(other.OutputFormat)
                ) && 
                (
                    this.CopyMetadata == other.CopyMetadata ||
                    this.CopyMetadata != null &&
                    this.CopyMetadata.Equals(other.CopyMetadata)
                ) && 
                (
                    this.TemplateFileContent == other.TemplateFileContent ||
                    this.TemplateFileContent != null &&
                    this.TemplateFileContent.Equals(other.TemplateFileContent)
                ) && 
                (
                    this.ViewsToConvert == other.ViewsToConvert ||
                    this.ViewsToConvert != null &&
                    this.ViewsToConvert.Equals(other.ViewsToConvert)
                ) && 
                (
                    this.ConvertAttachments == other.ConvertAttachments ||
                    this.ConvertAttachments != null &&
                    this.ConvertAttachments.Equals(other.ConvertAttachments)
                ) && 
                (
                    this.AttachmentMergeMode == other.AttachmentMergeMode ||
                    this.AttachmentMergeMode != null &&
                    this.AttachmentMergeMode.Equals(other.AttachmentMergeMode)
                ) && 
                (
                    this.UnsupportedAttachmentBehaviour == other.UnsupportedAttachmentBehaviour ||
                    this.UnsupportedAttachmentBehaviour != null &&
                    this.UnsupportedAttachmentBehaviour.Equals(other.UnsupportedAttachmentBehaviour)
                ) && 
                (
                    this.BreakMergeOnError == other.BreakMergeOnError ||
                    this.BreakMergeOnError != null &&
                    this.BreakMergeOnError.Equals(other.BreakMergeOnError)
                ) && 
                (
                    this.IncludeAttachmentTypes == other.IncludeAttachmentTypes ||
                    this.IncludeAttachmentTypes != null &&
                    this.IncludeAttachmentTypes.Equals(other.IncludeAttachmentTypes)
                ) && 
                (
                    this.ExcludeAttachmentTypes == other.ExcludeAttachmentTypes ||
                    this.ExcludeAttachmentTypes != null &&
                    this.ExcludeAttachmentTypes.Equals(other.ExcludeAttachmentTypes)
                ) && 
                (
                    this.DefaultPaperSize == other.DefaultPaperSize ||
                    this.DefaultPaperSize != null &&
                    this.DefaultPaperSize.Equals(other.DefaultPaperSize)
                ) && 
                (
                    this.DefaultPaperSizeCustom == other.DefaultPaperSizeCustom ||
                    this.DefaultPaperSizeCustom != null &&
                    this.DefaultPaperSizeCustom.Equals(other.DefaultPaperSizeCustom)
                ) && 
                (
                    this.ForcePaperSize == other.ForcePaperSize ||
                    this.ForcePaperSize != null &&
                    this.ForcePaperSize.Equals(other.ForcePaperSize)
                ) && 
                (
                    this.ForcePaperSizeCustom == other.ForcePaperSizeCustom ||
                    this.ForcePaperSizeCustom != null &&
                    this.ForcePaperSizeCustom.Equals(other.ForcePaperSizeCustom)
                ) && 
                (
                    this.DefaultPageOrientation == other.DefaultPageOrientation ||
                    this.DefaultPageOrientation != null &&
                    this.DefaultPageOrientation.Equals(other.DefaultPageOrientation)
                ) && 
                (
                    this.ForcePageOrientation == other.ForcePageOrientation ||
                    this.ForcePageOrientation != null &&
                    this.ForcePageOrientation.Equals(other.ForcePageOrientation)
                ) && 
                (
                    this.StartPage == other.StartPage ||
                    this.StartPage != null &&
                    this.StartPage.Equals(other.StartPage)
                ) && 
                (
                    this.EndPage == other.EndPage ||
                    this.EndPage != null &&
                    this.EndPage.Equals(other.EndPage)
                ) && 
                (
                    this.Quality == other.Quality ||
                    this.Quality != null &&
                    this.Quality.Equals(other.Quality)
                ) && 
                (
                    this.OverrideSettings == other.OverrideSettings ||
                    this.OverrideSettings != null &&
                    this.OverrideSettings.Equals(other.OverrideSettings)
                ) && 
                (
                    this.FailOnError == other.FailOnError ||
                    this.FailOnError != null &&
                    this.FailOnError.Equals(other.FailOnError)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.UseAsyncPattern != null)
                    hash = hash * 59 + this.UseAsyncPattern.GetHashCode();
                if (this.SourceFileName != null)
                    hash = hash * 59 + this.SourceFileName.GetHashCode();
                if (this.SharepointFile != null)
                    hash = hash * 59 + this.SharepointFile.GetHashCode();
                if (this.SourceFileContent != null)
                    hash = hash * 59 + this.SourceFileContent.GetHashCode();
                if (this.OutputFormat != null)
                    hash = hash * 59 + this.OutputFormat.GetHashCode();
                if (this.CopyMetadata != null)
                    hash = hash * 59 + this.CopyMetadata.GetHashCode();
                if (this.TemplateFileContent != null)
                    hash = hash * 59 + this.TemplateFileContent.GetHashCode();
                if (this.ViewsToConvert != null)
                    hash = hash * 59 + this.ViewsToConvert.GetHashCode();
                if (this.ConvertAttachments != null)
                    hash = hash * 59 + this.ConvertAttachments.GetHashCode();
                if (this.AttachmentMergeMode != null)
                    hash = hash * 59 + this.AttachmentMergeMode.GetHashCode();
                if (this.UnsupportedAttachmentBehaviour != null)
                    hash = hash * 59 + this.UnsupportedAttachmentBehaviour.GetHashCode();
                if (this.BreakMergeOnError != null)
                    hash = hash * 59 + this.BreakMergeOnError.GetHashCode();
                if (this.IncludeAttachmentTypes != null)
                    hash = hash * 59 + this.IncludeAttachmentTypes.GetHashCode();
                if (this.ExcludeAttachmentTypes != null)
                    hash = hash * 59 + this.ExcludeAttachmentTypes.GetHashCode();
                if (this.DefaultPaperSize != null)
                    hash = hash * 59 + this.DefaultPaperSize.GetHashCode();
                if (this.DefaultPaperSizeCustom != null)
                    hash = hash * 59 + this.DefaultPaperSizeCustom.GetHashCode();
                if (this.ForcePaperSize != null)
                    hash = hash * 59 + this.ForcePaperSize.GetHashCode();
                if (this.ForcePaperSizeCustom != null)
                    hash = hash * 59 + this.ForcePaperSizeCustom.GetHashCode();
                if (this.DefaultPageOrientation != null)
                    hash = hash * 59 + this.DefaultPageOrientation.GetHashCode();
                if (this.ForcePageOrientation != null)
                    hash = hash * 59 + this.ForcePageOrientation.GetHashCode();
                if (this.StartPage != null)
                    hash = hash * 59 + this.StartPage.GetHashCode();
                if (this.EndPage != null)
                    hash = hash * 59 + this.EndPage.GetHashCode();
                if (this.Quality != null)
                    hash = hash * 59 + this.Quality.GetHashCode();
                if (this.OverrideSettings != null)
                    hash = hash * 59 + this.OverrideSettings.GetHashCode();
                if (this.FailOnError != null)
                    hash = hash * 59 + this.FailOnError.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
