/* 
 * Muhimbi PDF
 *
 * Convert, Merge, Watermark, Secure and OCR files.
 *
 * OpenAPI spec version: 9.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Muhimbi.PDF.Online.Client.Model
{
    /// <summary>
    /// Parameters for SplitPdf operation
    /// </summary>
    [DataContract]
    public partial class SplitPdfData :  IEquatable<SplitPdfData>, IValidatableObject
    {
        /// <summary>
        /// Split by option
        /// </summary>
        /// <value>Split by option</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FileSplitTypeEnum
        {
            
            /// <summary>
            /// Enum ByNumberOfPages for "ByNumberOfPages"
            /// </summary>
            [EnumMember(Value = "ByNumberOfPages")]
            ByNumberOfPages,
            
            /// <summary>
            /// Enum ByBookmarkLevel for "ByBookmarkLevel"
            /// </summary>
            [EnumMember(Value = "ByBookmarkLevel")]
            ByBookmarkLevel
        }

        /// <summary>
        /// Split by option
        /// </summary>
        /// <value>Split by option</value>
        [DataMember(Name="file_split_type", EmitDefaultValue=false)]
        public FileSplitTypeEnum? FileSplitType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SplitPdfData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SplitPdfData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SplitPdfData" /> class.
        /// </summary>
        /// <param name="UseAsyncPattern">Use async behaviour for API request (default to false).</param>
        /// <param name="SourceFileName">Name of the source file including extension (required).</param>
        /// <param name="SourceFileContent">Content of the file to convert (required).</param>
        /// <param name="SharepointFile">SharepointFile.</param>
        /// <param name="FileSplitType">Split by option (required) (default to FileSplitTypeEnum.ByNumberOfPages).</param>
        /// <param name="SplitParameter">Split parameters (required) (default to 1).</param>
        /// <param name="FailOnError">Fail on error (default to true).</param>
        public SplitPdfData(bool? UseAsyncPattern = false, string SourceFileName = default(string), byte[] SourceFileContent = default(byte[]), SharepointFile SharepointFile = default(SharepointFile), FileSplitTypeEnum? FileSplitType = FileSplitTypeEnum.ByNumberOfPages, int? SplitParameter = 1, bool? FailOnError = true)
        {
            // to ensure "SourceFileName" is required (not null)
            if (SourceFileName == null)
            {
                throw new InvalidDataException("SourceFileName is a required property for SplitPdfData and cannot be null");
            }
            else
            {
                this.SourceFileName = SourceFileName;
            }
            // to ensure "SourceFileContent" is required (not null)
            if (SourceFileContent == null)
            {
                throw new InvalidDataException("SourceFileContent is a required property for SplitPdfData and cannot be null");
            }
            else
            {
                this.SourceFileContent = SourceFileContent;
            }
            // to ensure "FileSplitType" is required (not null)
            if (FileSplitType == null)
            {
                throw new InvalidDataException("FileSplitType is a required property for SplitPdfData and cannot be null");
            }
            else
            {
                this.FileSplitType = FileSplitType;
            }
            // to ensure "SplitParameter" is required (not null)
            if (SplitParameter == null)
            {
                throw new InvalidDataException("SplitParameter is a required property for SplitPdfData and cannot be null");
            }
            else
            {
                this.SplitParameter = SplitParameter;
            }
            // use default value if no "UseAsyncPattern" provided
            if (UseAsyncPattern == null)
            {
                this.UseAsyncPattern = false;
            }
            else
            {
                this.UseAsyncPattern = UseAsyncPattern;
            }
            this.SharepointFile = SharepointFile;
            // use default value if no "FailOnError" provided
            if (FailOnError == null)
            {
                this.FailOnError = true;
            }
            else
            {
                this.FailOnError = FailOnError;
            }
        }
        
        /// <summary>
        /// Use async behaviour for API request
        /// </summary>
        /// <value>Use async behaviour for API request</value>
        [DataMember(Name="use_async_pattern", EmitDefaultValue=false)]
        public bool? UseAsyncPattern { get; set; }
        /// <summary>
        /// Name of the source file including extension
        /// </summary>
        /// <value>Name of the source file including extension</value>
        [DataMember(Name="source_file_name", EmitDefaultValue=false)]
        public string SourceFileName { get; set; }
        /// <summary>
        /// Content of the file to convert
        /// </summary>
        /// <value>Content of the file to convert</value>
        [DataMember(Name="source_file_content", EmitDefaultValue=false)]
        public byte[] SourceFileContent { get; set; }
        /// <summary>
        /// Gets or Sets SharepointFile
        /// </summary>
        [DataMember(Name="sharepoint_file", EmitDefaultValue=false)]
        public SharepointFile SharepointFile { get; set; }
        /// <summary>
        /// Split parameters
        /// </summary>
        /// <value>Split parameters</value>
        [DataMember(Name="split_parameter", EmitDefaultValue=false)]
        public int? SplitParameter { get; set; }
        /// <summary>
        /// Fail on error
        /// </summary>
        /// <value>Fail on error</value>
        [DataMember(Name="fail_on_error", EmitDefaultValue=false)]
        public bool? FailOnError { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SplitPdfData {\n");
            sb.Append("  UseAsyncPattern: ").Append(UseAsyncPattern).Append("\n");
            sb.Append("  SourceFileName: ").Append(SourceFileName).Append("\n");
            sb.Append("  SourceFileContent: ").Append(SourceFileContent).Append("\n");
            sb.Append("  SharepointFile: ").Append(SharepointFile).Append("\n");
            sb.Append("  FileSplitType: ").Append(FileSplitType).Append("\n");
            sb.Append("  SplitParameter: ").Append(SplitParameter).Append("\n");
            sb.Append("  FailOnError: ").Append(FailOnError).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SplitPdfData);
        }

        /// <summary>
        /// Returns true if SplitPdfData instances are equal
        /// </summary>
        /// <param name="other">Instance of SplitPdfData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SplitPdfData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.UseAsyncPattern == other.UseAsyncPattern ||
                    this.UseAsyncPattern != null &&
                    this.UseAsyncPattern.Equals(other.UseAsyncPattern)
                ) && 
                (
                    this.SourceFileName == other.SourceFileName ||
                    this.SourceFileName != null &&
                    this.SourceFileName.Equals(other.SourceFileName)
                ) && 
                (
                    this.SourceFileContent == other.SourceFileContent ||
                    this.SourceFileContent != null &&
                    this.SourceFileContent.Equals(other.SourceFileContent)
                ) && 
                (
                    this.SharepointFile == other.SharepointFile ||
                    this.SharepointFile != null &&
                    this.SharepointFile.Equals(other.SharepointFile)
                ) && 
                (
                    this.FileSplitType == other.FileSplitType ||
                    this.FileSplitType != null &&
                    this.FileSplitType.Equals(other.FileSplitType)
                ) && 
                (
                    this.SplitParameter == other.SplitParameter ||
                    this.SplitParameter != null &&
                    this.SplitParameter.Equals(other.SplitParameter)
                ) && 
                (
                    this.FailOnError == other.FailOnError ||
                    this.FailOnError != null &&
                    this.FailOnError.Equals(other.FailOnError)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.UseAsyncPattern != null)
                    hash = hash * 59 + this.UseAsyncPattern.GetHashCode();
                if (this.SourceFileName != null)
                    hash = hash * 59 + this.SourceFileName.GetHashCode();
                if (this.SourceFileContent != null)
                    hash = hash * 59 + this.SourceFileContent.GetHashCode();
                if (this.SharepointFile != null)
                    hash = hash * 59 + this.SharepointFile.GetHashCode();
                if (this.FileSplitType != null)
                    hash = hash * 59 + this.FileSplitType.GetHashCode();
                if (this.SplitParameter != null)
                    hash = hash * 59 + this.SplitParameter.GetHashCode();
                if (this.FailOnError != null)
                    hash = hash * 59 + this.FailOnError.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
