<?php
/**
 * ConvertPowerpointData
 *
 * PHP version 5
 *
 * @category Class
 * @package  MuhimbiPDFOnline\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Muhimbi PDF
 *
 * Convert, Merge, Watermark, Secure and OCR files.
 *
 * OpenAPI spec version: 9.16
 * Contact: support@muhimbi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MuhimbiPDFOnline\Client\Model;

use \ArrayAccess;

/**
 * ConvertPowerpointData Class Doc Comment
 *
 * @category    Class
 * @description Parameters for Convert Excel operation
 * @package     MuhimbiPDFOnline\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConvertPowerpointData implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'convert_powerpoint_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'use_async_pattern' => 'bool',
        'source_file_name' => 'string',
        'sharepoint_file' => '\MuhimbiPDFOnline\Client\Model\SharepointFile',
        'source_file_content' => 'string',
        'output_format' => 'string',
        'copy_metadata' => 'bool',
        'range' => 'string',
        'print_output_type' => 'string',
        'frame_slides' => 'bool',
        'start_page' => 'int',
        'end_page' => 'int',
        'quality' => 'string',
        'override_settings' => 'string',
        'fail_on_error' => 'bool'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'use_async_pattern' => 'use_async_pattern',
        'source_file_name' => 'source_file_name',
        'sharepoint_file' => 'sharepoint_file',
        'source_file_content' => 'source_file_content',
        'output_format' => 'output_format',
        'copy_metadata' => 'copy_metadata',
        'range' => 'range',
        'print_output_type' => 'print_output_type',
        'frame_slides' => 'frame_slides',
        'start_page' => 'start_page',
        'end_page' => 'end_page',
        'quality' => 'quality',
        'override_settings' => 'override_settings',
        'fail_on_error' => 'fail_on_error'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'use_async_pattern' => 'setUseAsyncPattern',
        'source_file_name' => 'setSourceFileName',
        'sharepoint_file' => 'setSharepointFile',
        'source_file_content' => 'setSourceFileContent',
        'output_format' => 'setOutputFormat',
        'copy_metadata' => 'setCopyMetadata',
        'range' => 'setRange',
        'print_output_type' => 'setPrintOutputType',
        'frame_slides' => 'setFrameSlides',
        'start_page' => 'setStartPage',
        'end_page' => 'setEndPage',
        'quality' => 'setQuality',
        'override_settings' => 'setOverrideSettings',
        'fail_on_error' => 'setFailOnError'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'use_async_pattern' => 'getUseAsyncPattern',
        'source_file_name' => 'getSourceFileName',
        'sharepoint_file' => 'getSharepointFile',
        'source_file_content' => 'getSourceFileContent',
        'output_format' => 'getOutputFormat',
        'copy_metadata' => 'getCopyMetadata',
        'range' => 'getRange',
        'print_output_type' => 'getPrintOutputType',
        'frame_slides' => 'getFrameSlides',
        'start_page' => 'getStartPage',
        'end_page' => 'getEndPage',
        'quality' => 'getQuality',
        'override_settings' => 'getOverrideSettings',
        'fail_on_error' => 'getFailOnError'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const OUTPUT_FORMAT_PDF = 'PDF';
    const OUTPUT_FORMAT_XPS = 'XPS';
    const OUTPUT_FORMAT_MHT = 'MHT';
    const OUTPUT_FORMAT_XML = 'XML';
    const OUTPUT_FORMAT_PPT = 'PPT';
    const OUTPUT_FORMAT_PPTX = 'PPTX';
    const OUTPUT_FORMAT_ODP = 'ODP';
    const OUTPUT_FORMAT_PPS = 'PPS';
    const OUTPUT_FORMAT_PPSX = 'PPSX';
    const RANGE_VISIBLE_DOCUMENTS = 'VisibleDocuments';
    const RANGE_ALL_DOCUMENTS = 'AllDocuments';
    const RANGE_ACTIVE_DOCUMENTS = 'ActiveDocuments';
    const PRINT_OUTPUT_TYPE_SLIDES = 'Slides';
    const PRINT_OUTPUT_TYPE_ONE_SLIDE_HANDOUTS = 'OneSlideHandouts';
    const PRINT_OUTPUT_TYPE_TWO_SLIDE_HANDOUTS = 'TwoSlideHandouts';
    const PRINT_OUTPUT_TYPE_THREE_SLIDE_HANDOUTS = 'ThreeSlideHandouts';
    const PRINT_OUTPUT_TYPE_FOUR_SLIDE_HANDOUTS = 'FourSlideHandouts';
    const PRINT_OUTPUT_TYPE_SIX_SLIDE_HANDOUTS = 'SixSlideHandouts';
    const PRINT_OUTPUT_TYPE_NINE_SLIDE_HANDOUTS = 'NineSlideHandouts';
    const PRINT_OUTPUT_TYPE_NOTES_PAGES = 'NotesPages';
    const PRINT_OUTPUT_TYPE_OUTLINE = 'Outline';
    const QUALITY_OPTIMIZE_FOR_PRINT = 'OptimizeForPrint';
    const QUALITY_OPTIMIZE_FOR_ON_SCREEN = 'OptimizeForOnScreen';
    const QUALITY_ORIGINAL = 'Original';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getOutputFormatAllowableValues()
    {
        return [
            self::OUTPUT_FORMAT_PDF,
            self::OUTPUT_FORMAT_XPS,
            self::OUTPUT_FORMAT_MHT,
            self::OUTPUT_FORMAT_XML,
            self::OUTPUT_FORMAT_PPT,
            self::OUTPUT_FORMAT_PPTX,
            self::OUTPUT_FORMAT_ODP,
            self::OUTPUT_FORMAT_PPS,
            self::OUTPUT_FORMAT_PPSX,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getRangeAllowableValues()
    {
        return [
            self::RANGE_VISIBLE_DOCUMENTS,
            self::RANGE_ALL_DOCUMENTS,
            self::RANGE_ACTIVE_DOCUMENTS,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getPrintOutputTypeAllowableValues()
    {
        return [
            self::PRINT_OUTPUT_TYPE_SLIDES,
            self::PRINT_OUTPUT_TYPE_ONE_SLIDE_HANDOUTS,
            self::PRINT_OUTPUT_TYPE_TWO_SLIDE_HANDOUTS,
            self::PRINT_OUTPUT_TYPE_THREE_SLIDE_HANDOUTS,
            self::PRINT_OUTPUT_TYPE_FOUR_SLIDE_HANDOUTS,
            self::PRINT_OUTPUT_TYPE_SIX_SLIDE_HANDOUTS,
            self::PRINT_OUTPUT_TYPE_NINE_SLIDE_HANDOUTS,
            self::PRINT_OUTPUT_TYPE_NOTES_PAGES,
            self::PRINT_OUTPUT_TYPE_OUTLINE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getQualityAllowableValues()
    {
        return [
            self::QUALITY_OPTIMIZE_FOR_PRINT,
            self::QUALITY_OPTIMIZE_FOR_ON_SCREEN,
            self::QUALITY_ORIGINAL,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['use_async_pattern'] = isset($data['use_async_pattern']) ? $data['use_async_pattern'] : false;
        $this->container['source_file_name'] = isset($data['source_file_name']) ? $data['source_file_name'] : null;
        $this->container['sharepoint_file'] = isset($data['sharepoint_file']) ? $data['sharepoint_file'] : null;
        $this->container['source_file_content'] = isset($data['source_file_content']) ? $data['source_file_content'] : null;
        $this->container['output_format'] = isset($data['output_format']) ? $data['output_format'] : 'PDF';
        $this->container['copy_metadata'] = isset($data['copy_metadata']) ? $data['copy_metadata'] : false;
        $this->container['range'] = isset($data['range']) ? $data['range'] : null;
        $this->container['print_output_type'] = isset($data['print_output_type']) ? $data['print_output_type'] : 'Slides';
        $this->container['frame_slides'] = isset($data['frame_slides']) ? $data['frame_slides'] : true;
        $this->container['start_page'] = isset($data['start_page']) ? $data['start_page'] : null;
        $this->container['end_page'] = isset($data['end_page']) ? $data['end_page'] : null;
        $this->container['quality'] = isset($data['quality']) ? $data['quality'] : null;
        $this->container['override_settings'] = isset($data['override_settings']) ? $data['override_settings'] : null;
        $this->container['fail_on_error'] = isset($data['fail_on_error']) ? $data['fail_on_error'] : true;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['use_async_pattern'] === null) {
            $invalid_properties[] = "'use_async_pattern' can't be null";
        }
        if ($this->container['source_file_name'] === null) {
            $invalid_properties[] = "'source_file_name' can't be null";
        }
        if ($this->container['source_file_content'] === null) {
            $invalid_properties[] = "'source_file_content' can't be null";
        }
        if ($this->container['output_format'] === null) {
            $invalid_properties[] = "'output_format' can't be null";
        }
        $allowed_values = ["PDF", "XPS", "MHT", "XML", "PPT", "PPTX", "ODP", "PPS", "PPSX"];
        if (!in_array($this->container['output_format'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'output_format', must be one of 'PDF', 'XPS', 'MHT', 'XML', 'PPT', 'PPTX', 'ODP', 'PPS', 'PPSX'.";
        }

        if ($this->container['copy_metadata'] === null) {
            $invalid_properties[] = "'copy_metadata' can't be null";
        }
        $allowed_values = ["VisibleDocuments", "AllDocuments", "ActiveDocuments"];
        if (!in_array($this->container['range'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'range', must be one of 'VisibleDocuments', 'AllDocuments', 'ActiveDocuments'.";
        }

        $allowed_values = ["Slides", "OneSlideHandouts", "TwoSlideHandouts", "ThreeSlideHandouts", "FourSlideHandouts", "SixSlideHandouts", "NineSlideHandouts", "NotesPages", "Outline"];
        if (!in_array($this->container['print_output_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'print_output_type', must be one of 'Slides', 'OneSlideHandouts', 'TwoSlideHandouts', 'ThreeSlideHandouts', 'FourSlideHandouts', 'SixSlideHandouts', 'NineSlideHandouts', 'NotesPages', 'Outline'.";
        }

        $allowed_values = ["OptimizeForPrint", "OptimizeForOnScreen", "Original"];
        if (!in_array($this->container['quality'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'quality', must be one of 'OptimizeForPrint', 'OptimizeForOnScreen', 'Original'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['use_async_pattern'] === null) {
            return false;
        }
        if ($this->container['source_file_name'] === null) {
            return false;
        }
        if ($this->container['source_file_content'] === null) {
            return false;
        }
        if ($this->container['output_format'] === null) {
            return false;
        }
        $allowed_values = ["PDF", "XPS", "MHT", "XML", "PPT", "PPTX", "ODP", "PPS", "PPSX"];
        if (!in_array($this->container['output_format'], $allowed_values)) {
            return false;
        }
        if ($this->container['copy_metadata'] === null) {
            return false;
        }
        $allowed_values = ["VisibleDocuments", "AllDocuments", "ActiveDocuments"];
        if (!in_array($this->container['range'], $allowed_values)) {
            return false;
        }
        $allowed_values = ["Slides", "OneSlideHandouts", "TwoSlideHandouts", "ThreeSlideHandouts", "FourSlideHandouts", "SixSlideHandouts", "NineSlideHandouts", "NotesPages", "Outline"];
        if (!in_array($this->container['print_output_type'], $allowed_values)) {
            return false;
        }
        $allowed_values = ["OptimizeForPrint", "OptimizeForOnScreen", "Original"];
        if (!in_array($this->container['quality'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets use_async_pattern
     * @return bool
     */
    public function getUseAsyncPattern()
    {
        return $this->container['use_async_pattern'];
    }

    /**
     * Sets use_async_pattern
     * @param bool $use_async_pattern Use async behaviour for API request
     * @return $this
     */
    public function setUseAsyncPattern($use_async_pattern)
    {
        $this->container['use_async_pattern'] = $use_async_pattern;

        return $this;
    }

    /**
     * Gets source_file_name
     * @return string
     */
    public function getSourceFileName()
    {
        return $this->container['source_file_name'];
    }

    /**
     * Sets source_file_name
     * @param string $source_file_name Name of the source file including extension
     * @return $this
     */
    public function setSourceFileName($source_file_name)
    {
        $this->container['source_file_name'] = $source_file_name;

        return $this;
    }

    /**
     * Gets sharepoint_file
     * @return \MuhimbiPDFOnline\Client\Model\SharepointFile
     */
    public function getSharepointFile()
    {
        return $this->container['sharepoint_file'];
    }

    /**
     * Sets sharepoint_file
     * @param \MuhimbiPDFOnline\Client\Model\SharepointFile $sharepoint_file
     * @return $this
     */
    public function setSharepointFile($sharepoint_file)
    {
        $this->container['sharepoint_file'] = $sharepoint_file;

        return $this;
    }

    /**
     * Gets source_file_content
     * @return string
     */
    public function getSourceFileContent()
    {
        return $this->container['source_file_content'];
    }

    /**
     * Sets source_file_content
     * @param string $source_file_content Content of the file to convert
     * @return $this
     */
    public function setSourceFileContent($source_file_content)
    {
        $this->container['source_file_content'] = $source_file_content;

        return $this;
    }

    /**
     * Gets output_format
     * @return string
     */
    public function getOutputFormat()
    {
        return $this->container['output_format'];
    }

    /**
     * Sets output_format
     * @param string $output_format Output format
     * @return $this
     */
    public function setOutputFormat($output_format)
    {
        $allowed_values = array('PDF', 'XPS', 'MHT', 'XML', 'PPT', 'PPTX', 'ODP', 'PPS', 'PPSX');
        if ((!in_array($output_format, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'output_format', must be one of 'PDF', 'XPS', 'MHT', 'XML', 'PPT', 'PPTX', 'ODP', 'PPS', 'PPSX'");
        }
        $this->container['output_format'] = $output_format;

        return $this;
    }

    /**
     * Gets copy_metadata
     * @return bool
     */
    public function getCopyMetadata()
    {
        return $this->container['copy_metadata'];
    }

    /**
     * Sets copy_metadata
     * @param bool $copy_metadata Copy metadata (Only for SharePoint operations)
     * @return $this
     */
    public function setCopyMetadata($copy_metadata)
    {
        $this->container['copy_metadata'] = $copy_metadata;

        return $this;
    }

    /**
     * Gets range
     * @return string
     */
    public function getRange()
    {
        return $this->container['range'];
    }

    /**
     * Sets range
     * @param string $range Specify which parts of the document to process
     * @return $this
     */
    public function setRange($range)
    {
        $allowed_values = array('VisibleDocuments', 'AllDocuments', 'ActiveDocuments');
        if (!is_null($range) && (!in_array($range, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'range', must be one of 'VisibleDocuments', 'AllDocuments', 'ActiveDocuments'");
        }
        $this->container['range'] = $range;

        return $this;
    }

    /**
     * Gets print_output_type
     * @return string
     */
    public function getPrintOutputType()
    {
        return $this->container['print_output_type'];
    }

    /**
     * Sets print_output_type
     * @param string $print_output_type Specify how you would like the output to be arranged
     * @return $this
     */
    public function setPrintOutputType($print_output_type)
    {
        $allowed_values = array('Slides', 'OneSlideHandouts', 'TwoSlideHandouts', 'ThreeSlideHandouts', 'FourSlideHandouts', 'SixSlideHandouts', 'NineSlideHandouts', 'NotesPages', 'Outline');
        if (!is_null($print_output_type) && (!in_array($print_output_type, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'print_output_type', must be one of 'Slides', 'OneSlideHandouts', 'TwoSlideHandouts', 'ThreeSlideHandouts', 'FourSlideHandouts', 'SixSlideHandouts', 'NineSlideHandouts', 'NotesPages', 'Outline'");
        }
        $this->container['print_output_type'] = $print_output_type;

        return $this;
    }

    /**
     * Gets frame_slides
     * @return bool
     */
    public function getFrameSlides()
    {
        return $this->container['frame_slides'];
    }

    /**
     * Sets frame_slides
     * @param bool $frame_slides Include a frame / border around the slides
     * @return $this
     */
    public function setFrameSlides($frame_slides)
    {
        $this->container['frame_slides'] = $frame_slides;

        return $this;
    }

    /**
     * Gets start_page
     * @return int
     */
    public function getStartPage()
    {
        return $this->container['start_page'];
    }

    /**
     * Sets start_page
     * @param int $start_page The first page to include
     * @return $this
     */
    public function setStartPage($start_page)
    {
        $this->container['start_page'] = $start_page;

        return $this;
    }

    /**
     * Gets end_page
     * @return int
     */
    public function getEndPage()
    {
        return $this->container['end_page'];
    }

    /**
     * Sets end_page
     * @param int $end_page The last page to include
     * @return $this
     */
    public function setEndPage($end_page)
    {
        $this->container['end_page'] = $end_page;

        return $this;
    }

    /**
     * Gets quality
     * @return string
     */
    public function getQuality()
    {
        return $this->container['quality'];
    }

    /**
     * Sets quality
     * @param string $quality Quality of the output file
     * @return $this
     */
    public function setQuality($quality)
    {
        $allowed_values = array('OptimizeForPrint', 'OptimizeForOnScreen', 'Original');
        if (!is_null($quality) && (!in_array($quality, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'quality', must be one of 'OptimizeForPrint', 'OptimizeForOnScreen', 'Original'");
        }
        $this->container['quality'] = $quality;

        return $this;
    }

    /**
     * Gets override_settings
     * @return string
     */
    public function getOverrideSettings()
    {
        return $this->container['override_settings'];
    }

    /**
     * Sets override_settings
     * @param string $override_settings Optional settings using Muhimbi's XML syntax
     * @return $this
     */
    public function setOverrideSettings($override_settings)
    {
        $this->container['override_settings'] = $override_settings;

        return $this;
    }

    /**
     * Gets fail_on_error
     * @return bool
     */
    public function getFailOnError()
    {
        return $this->container['fail_on_error'];
    }

    /**
     * Sets fail_on_error
     * @param bool $fail_on_error Fail on error
     * @return $this
     */
    public function setFailOnError($fail_on_error)
    {
        $this->container['fail_on_error'] = $fail_on_error;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\MuhimbiPDFOnline\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\MuhimbiPDFOnline\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


