<?php
/**
 * LinearBarcodeWatermarkData
 *
 * PHP version 5
 *
 * @category Class
 * @package  MuhimbiPDFOnline\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Muhimbi PDF
 *
 * Convert, Merge, Watermark, Secure and OCR files.
 *
 * OpenAPI spec version: 9.14.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MuhimbiPDFOnline\Client\Model;

use \ArrayAccess;

/**
 * LinearBarcodeWatermarkData Class Doc Comment
 *
 * @category    Class
 * @description Parameters for LinearBarcodeWatermark operation
 * @package     MuhimbiPDFOnline\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinearBarcodeWatermarkData implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'linear_barcode_watermark_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'source_file_name' => 'string',
        'use_async_pattern' => 'bool',
        'source_file_content' => 'string',
        'content' => 'string',
        'sharepoint_file' => '\MuhimbiPDFOnline\Client\Model\SharepointFile',
        'barcode_type' => 'string',
        'omit_start_stop_symbols' => 'string',
        'disable_checkdigit' => 'string',
        'show_checkdigit' => 'string',
        'margin' => 'string',
        'font_family_name' => 'string',
        'font_size' => 'string',
        'font_style' => 'string',
        'label_placement' => 'string',
        'position' => 'string',
        'width' => 'string',
        'height' => 'string',
        'x' => 'string',
        'y' => 'string',
        'layer' => 'string',
        'rotation' => 'string',
        'opacity' => 'string',
        'fill_color' => 'string',
        'line_color' => 'string',
        'start_page' => 'int',
        'end_page' => 'int',
        'page_interval' => 'int',
        'page_orientation' => 'string',
        'print_only' => 'string',
        'start_section' => 'int',
        'end_section' => 'int',
        'page_type' => 'string',
        'fail_on_error' => 'bool'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'source_file_name' => 'source_file_name',
        'use_async_pattern' => 'use_async_pattern',
        'source_file_content' => 'source_file_content',
        'content' => 'content',
        'sharepoint_file' => 'sharepoint_file',
        'barcode_type' => 'barcode_type',
        'omit_start_stop_symbols' => 'omit_start_stop_symbols',
        'disable_checkdigit' => 'disable_checkdigit',
        'show_checkdigit' => 'show_checkdigit',
        'margin' => 'margin',
        'font_family_name' => 'font_family_name',
        'font_size' => 'font_size',
        'font_style' => 'font_style',
        'label_placement' => 'label_placement',
        'position' => 'position',
        'width' => 'width',
        'height' => 'height',
        'x' => 'x',
        'y' => 'y',
        'layer' => 'layer',
        'rotation' => 'rotation',
        'opacity' => 'opacity',
        'fill_color' => 'fill_color',
        'line_color' => 'line_color',
        'start_page' => 'start_page',
        'end_page' => 'end_page',
        'page_interval' => 'page_interval',
        'page_orientation' => 'page_orientation',
        'print_only' => 'print_only',
        'start_section' => 'start_section',
        'end_section' => 'end_section',
        'page_type' => 'page_type',
        'fail_on_error' => 'fail_on_error'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'source_file_name' => 'setSourceFileName',
        'use_async_pattern' => 'setUseAsyncPattern',
        'source_file_content' => 'setSourceFileContent',
        'content' => 'setContent',
        'sharepoint_file' => 'setSharepointFile',
        'barcode_type' => 'setBarcodeType',
        'omit_start_stop_symbols' => 'setOmitStartStopSymbols',
        'disable_checkdigit' => 'setDisableCheckdigit',
        'show_checkdigit' => 'setShowCheckdigit',
        'margin' => 'setMargin',
        'font_family_name' => 'setFontFamilyName',
        'font_size' => 'setFontSize',
        'font_style' => 'setFontStyle',
        'label_placement' => 'setLabelPlacement',
        'position' => 'setPosition',
        'width' => 'setWidth',
        'height' => 'setHeight',
        'x' => 'setX',
        'y' => 'setY',
        'layer' => 'setLayer',
        'rotation' => 'setRotation',
        'opacity' => 'setOpacity',
        'fill_color' => 'setFillColor',
        'line_color' => 'setLineColor',
        'start_page' => 'setStartPage',
        'end_page' => 'setEndPage',
        'page_interval' => 'setPageInterval',
        'page_orientation' => 'setPageOrientation',
        'print_only' => 'setPrintOnly',
        'start_section' => 'setStartSection',
        'end_section' => 'setEndSection',
        'page_type' => 'setPageType',
        'fail_on_error' => 'setFailOnError'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'source_file_name' => 'getSourceFileName',
        'use_async_pattern' => 'getUseAsyncPattern',
        'source_file_content' => 'getSourceFileContent',
        'content' => 'getContent',
        'sharepoint_file' => 'getSharepointFile',
        'barcode_type' => 'getBarcodeType',
        'omit_start_stop_symbols' => 'getOmitStartStopSymbols',
        'disable_checkdigit' => 'getDisableCheckdigit',
        'show_checkdigit' => 'getShowCheckdigit',
        'margin' => 'getMargin',
        'font_family_name' => 'getFontFamilyName',
        'font_size' => 'getFontSize',
        'font_style' => 'getFontStyle',
        'label_placement' => 'getLabelPlacement',
        'position' => 'getPosition',
        'width' => 'getWidth',
        'height' => 'getHeight',
        'x' => 'getX',
        'y' => 'getY',
        'layer' => 'getLayer',
        'rotation' => 'getRotation',
        'opacity' => 'getOpacity',
        'fill_color' => 'getFillColor',
        'line_color' => 'getLineColor',
        'start_page' => 'getStartPage',
        'end_page' => 'getEndPage',
        'page_interval' => 'getPageInterval',
        'page_orientation' => 'getPageOrientation',
        'print_only' => 'getPrintOnly',
        'start_section' => 'getStartSection',
        'end_section' => 'getEndSection',
        'page_type' => 'getPageType',
        'fail_on_error' => 'getFailOnError'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const BARCODE_TYPE_CODABAR = 'Codabar';
    const BARCODE_TYPE_CODE11 = 'Code11';
    const BARCODE_TYPE_CODE32 = 'Code32';
    const BARCODE_TYPE_CODE39 = 'Code39';
    const BARCODE_TYPE_CODE39_EXTENDED = 'Code39Extended';
    const BARCODE_TYPE_CODE93 = 'Code93';
    const BARCODE_TYPE_CODE93_EXTENDED = 'Code93Extended';
    const BARCODE_TYPE_CODE128 = 'Code128';
    const BARCODE_TYPE_CODE128_A = 'Code128A';
    const BARCODE_TYPE_CODE128_B = 'Code128B';
    const BARCODE_TYPE_CODE128_C = 'Code128C';
    const BARCODE_TYPE_GS1_CODE128 = 'GS1Code128';
    const BARCODE_TYPE_UPC_A = 'UPC_A';
    const OMIT_START_STOP_SYMBOLS_TRUE = 'true';
    const OMIT_START_STOP_SYMBOLS_FALSE = 'false';
    const DISABLE_CHECKDIGIT_TRUE = 'true';
    const DISABLE_CHECKDIGIT_FALSE = 'false';
    const SHOW_CHECKDIGIT_TRUE = 'true';
    const SHOW_CHECKDIGIT_FALSE = 'false';
    const LABEL_PLACEMENT_TOP_LEFT = 'Top Left';
    const LABEL_PLACEMENT_TOP_CENTER = 'Top Center';
    const LABEL_PLACEMENT_TOP_RIGHT = 'Top Right';
    const LABEL_PLACEMENT_NONE = 'None';
    const LABEL_PLACEMENT_BOTTOM_LEFT = 'Bottom Left';
    const LABEL_PLACEMENT_BOTTOM_CENTER = 'Bottom Center';
    const LABEL_PLACEMENT_BOTTOM_RIGHT = 'Bottom Right';
    const POSITION_TOP_LEFT = 'Top Left';
    const POSITION_TOP_CENTER = 'Top Center';
    const POSITION_TOP_RIGHT = 'Top Right';
    const POSITION_MIDDLE_LEFT = 'Middle Left';
    const POSITION_MIDDLE_CENTER = 'Middle Center';
    const POSITION_MIDDLE_RIGHT = 'Middle Right';
    const POSITION_BOTTOM_LEFT = 'Bottom Left';
    const POSITION_BOTTOM_CENTER = 'Bottom Center';
    const POSITION_BOTTOM_RIGHT = 'Bottom Right';
    const POSITION_ABSOLUTE = 'Absolute';
    const POSITION_RANDOM = 'Random';
    const LAYER_BACKGROUND = 'Background';
    const LAYER_FOREGROUND = 'Foreground';
    const PAGE_ORIENTATION_PORTRAIT = 'Portrait';
    const PAGE_ORIENTATION_LANDSCAPE = 'Landscape';
    const PAGE_ORIENTATION_BOTH = 'Both';
    const PRINT_ONLY_FALSE = 'false';
    const PRINT_ONLY_TRUE = 'true';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getBarcodeTypeAllowableValues()
    {
        return [
            self::BARCODE_TYPE_CODABAR,
            self::BARCODE_TYPE_CODE11,
            self::BARCODE_TYPE_CODE32,
            self::BARCODE_TYPE_CODE39,
            self::BARCODE_TYPE_CODE39_EXTENDED,
            self::BARCODE_TYPE_CODE93,
            self::BARCODE_TYPE_CODE93_EXTENDED,
            self::BARCODE_TYPE_CODE128,
            self::BARCODE_TYPE_CODE128_A,
            self::BARCODE_TYPE_CODE128_B,
            self::BARCODE_TYPE_CODE128_C,
            self::BARCODE_TYPE_GS1_CODE128,
            self::BARCODE_TYPE_UPC_A,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getOmitStartStopSymbolsAllowableValues()
    {
        return [
            self::OMIT_START_STOP_SYMBOLS_TRUE,
            self::OMIT_START_STOP_SYMBOLS_FALSE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getDisableCheckdigitAllowableValues()
    {
        return [
            self::DISABLE_CHECKDIGIT_TRUE,
            self::DISABLE_CHECKDIGIT_FALSE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getShowCheckdigitAllowableValues()
    {
        return [
            self::SHOW_CHECKDIGIT_TRUE,
            self::SHOW_CHECKDIGIT_FALSE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getLabelPlacementAllowableValues()
    {
        return [
            self::LABEL_PLACEMENT_TOP_LEFT,
            self::LABEL_PLACEMENT_TOP_CENTER,
            self::LABEL_PLACEMENT_TOP_RIGHT,
            self::LABEL_PLACEMENT_NONE,
            self::LABEL_PLACEMENT_BOTTOM_LEFT,
            self::LABEL_PLACEMENT_BOTTOM_CENTER,
            self::LABEL_PLACEMENT_BOTTOM_RIGHT,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getPositionAllowableValues()
    {
        return [
            self::POSITION_TOP_LEFT,
            self::POSITION_TOP_CENTER,
            self::POSITION_TOP_RIGHT,
            self::POSITION_MIDDLE_LEFT,
            self::POSITION_MIDDLE_CENTER,
            self::POSITION_MIDDLE_RIGHT,
            self::POSITION_BOTTOM_LEFT,
            self::POSITION_BOTTOM_CENTER,
            self::POSITION_BOTTOM_RIGHT,
            self::POSITION_ABSOLUTE,
            self::POSITION_RANDOM,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getLayerAllowableValues()
    {
        return [
            self::LAYER_BACKGROUND,
            self::LAYER_FOREGROUND,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getPageOrientationAllowableValues()
    {
        return [
            self::PAGE_ORIENTATION_PORTRAIT,
            self::PAGE_ORIENTATION_LANDSCAPE,
            self::PAGE_ORIENTATION_BOTH,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getPrintOnlyAllowableValues()
    {
        return [
            self::PRINT_ONLY_FALSE,
            self::PRINT_ONLY_TRUE,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['source_file_name'] = isset($data['source_file_name']) ? $data['source_file_name'] : null;
        $this->container['use_async_pattern'] = isset($data['use_async_pattern']) ? $data['use_async_pattern'] : false;
        $this->container['source_file_content'] = isset($data['source_file_content']) ? $data['source_file_content'] : null;
        $this->container['content'] = isset($data['content']) ? $data['content'] : null;
        $this->container['sharepoint_file'] = isset($data['sharepoint_file']) ? $data['sharepoint_file'] : null;
        $this->container['barcode_type'] = isset($data['barcode_type']) ? $data['barcode_type'] : 'Codabar';
        $this->container['omit_start_stop_symbols'] = isset($data['omit_start_stop_symbols']) ? $data['omit_start_stop_symbols'] : 'false';
        $this->container['disable_checkdigit'] = isset($data['disable_checkdigit']) ? $data['disable_checkdigit'] : 'false';
        $this->container['show_checkdigit'] = isset($data['show_checkdigit']) ? $data['show_checkdigit'] : 'false';
        $this->container['margin'] = isset($data['margin']) ? $data['margin'] : null;
        $this->container['font_family_name'] = isset($data['font_family_name']) ? $data['font_family_name'] : null;
        $this->container['font_size'] = isset($data['font_size']) ? $data['font_size'] : null;
        $this->container['font_style'] = isset($data['font_style']) ? $data['font_style'] : null;
        $this->container['label_placement'] = isset($data['label_placement']) ? $data['label_placement'] : 'Bottom Center';
        $this->container['position'] = isset($data['position']) ? $data['position'] : 'Middle Center';
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['x'] = isset($data['x']) ? $data['x'] : null;
        $this->container['y'] = isset($data['y']) ? $data['y'] : null;
        $this->container['layer'] = isset($data['layer']) ? $data['layer'] : 'Foreground';
        $this->container['rotation'] = isset($data['rotation']) ? $data['rotation'] : null;
        $this->container['opacity'] = isset($data['opacity']) ? $data['opacity'] : '100';
        $this->container['fill_color'] = isset($data['fill_color']) ? $data['fill_color'] : null;
        $this->container['line_color'] = isset($data['line_color']) ? $data['line_color'] : null;
        $this->container['start_page'] = isset($data['start_page']) ? $data['start_page'] : null;
        $this->container['end_page'] = isset($data['end_page']) ? $data['end_page'] : null;
        $this->container['page_interval'] = isset($data['page_interval']) ? $data['page_interval'] : null;
        $this->container['page_orientation'] = isset($data['page_orientation']) ? $data['page_orientation'] : 'Both';
        $this->container['print_only'] = isset($data['print_only']) ? $data['print_only'] : 'false';
        $this->container['start_section'] = isset($data['start_section']) ? $data['start_section'] : null;
        $this->container['end_section'] = isset($data['end_section']) ? $data['end_section'] : null;
        $this->container['page_type'] = isset($data['page_type']) ? $data['page_type'] : null;
        $this->container['fail_on_error'] = isset($data['fail_on_error']) ? $data['fail_on_error'] : true;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['use_async_pattern'] === null) {
            $invalid_properties[] = "'use_async_pattern' can't be null";
        }
        if ($this->container['source_file_content'] === null) {
            $invalid_properties[] = "'source_file_content' can't be null";
        }
        if ($this->container['content'] === null) {
            $invalid_properties[] = "'content' can't be null";
        }
        if ($this->container['barcode_type'] === null) {
            $invalid_properties[] = "'barcode_type' can't be null";
        }
        $allowed_values = ["Codabar", "Code11", "Code32", "Code39", "Code39Extended", "Code93", "Code93Extended", "Code128", "Code128A", "Code128B", "Code128C", "GS1Code128", "UPC_A"];
        if (!in_array($this->container['barcode_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'barcode_type', must be one of 'Codabar', 'Code11', 'Code32', 'Code39', 'Code39Extended', 'Code93', 'Code93Extended', 'Code128', 'Code128A', 'Code128B', 'Code128C', 'GS1Code128', 'UPC_A'.";
        }

        $allowed_values = ["true", "false"];
        if (!in_array($this->container['omit_start_stop_symbols'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'omit_start_stop_symbols', must be one of 'true', 'false'.";
        }

        if ($this->container['disable_checkdigit'] === null) {
            $invalid_properties[] = "'disable_checkdigit' can't be null";
        }
        $allowed_values = ["true", "false"];
        if (!in_array($this->container['disable_checkdigit'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'disable_checkdigit', must be one of 'true', 'false'.";
        }

        if ($this->container['show_checkdigit'] === null) {
            $invalid_properties[] = "'show_checkdigit' can't be null";
        }
        $allowed_values = ["true", "false"];
        if (!in_array($this->container['show_checkdigit'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'show_checkdigit', must be one of 'true', 'false'.";
        }

        $allowed_values = ["Top Left", "Top Center", "Top Right", "None", "Bottom Left", "Bottom Center", "Bottom Right"];
        if (!in_array($this->container['label_placement'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'label_placement', must be one of 'Top Left', 'Top Center', 'Top Right', 'None', 'Bottom Left', 'Bottom Center', 'Bottom Right'.";
        }

        if ($this->container['position'] === null) {
            $invalid_properties[] = "'position' can't be null";
        }
        $allowed_values = ["Top Left", "Top Center", "Top Right", "Middle Left", "Middle Center", "Middle Right", "Bottom Left", "Bottom Center", "Bottom Right", "Absolute", "Random"];
        if (!in_array($this->container['position'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'position', must be one of 'Top Left', 'Top Center', 'Top Right', 'Middle Left', 'Middle Center', 'Middle Right', 'Bottom Left', 'Bottom Center', 'Bottom Right', 'Absolute', 'Random'.";
        }

        if ($this->container['width'] === null) {
            $invalid_properties[] = "'width' can't be null";
        }
        if ($this->container['height'] === null) {
            $invalid_properties[] = "'height' can't be null";
        }
        $allowed_values = ["Background", "Foreground"];
        if (!in_array($this->container['layer'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'layer', must be one of 'Background', 'Foreground'.";
        }

        $allowed_values = ["Portrait", "Landscape", "Both"];
        if (!in_array($this->container['page_orientation'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'page_orientation', must be one of 'Portrait', 'Landscape', 'Both'.";
        }

        $allowed_values = ["false", "true"];
        if (!in_array($this->container['print_only'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'print_only', must be one of 'false', 'true'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['use_async_pattern'] === null) {
            return false;
        }
        if ($this->container['source_file_content'] === null) {
            return false;
        }
        if ($this->container['content'] === null) {
            return false;
        }
        if ($this->container['barcode_type'] === null) {
            return false;
        }
        $allowed_values = ["Codabar", "Code11", "Code32", "Code39", "Code39Extended", "Code93", "Code93Extended", "Code128", "Code128A", "Code128B", "Code128C", "GS1Code128", "UPC_A"];
        if (!in_array($this->container['barcode_type'], $allowed_values)) {
            return false;
        }
        $allowed_values = ["true", "false"];
        if (!in_array($this->container['omit_start_stop_symbols'], $allowed_values)) {
            return false;
        }
        if ($this->container['disable_checkdigit'] === null) {
            return false;
        }
        $allowed_values = ["true", "false"];
        if (!in_array($this->container['disable_checkdigit'], $allowed_values)) {
            return false;
        }
        if ($this->container['show_checkdigit'] === null) {
            return false;
        }
        $allowed_values = ["true", "false"];
        if (!in_array($this->container['show_checkdigit'], $allowed_values)) {
            return false;
        }
        $allowed_values = ["Top Left", "Top Center", "Top Right", "None", "Bottom Left", "Bottom Center", "Bottom Right"];
        if (!in_array($this->container['label_placement'], $allowed_values)) {
            return false;
        }
        if ($this->container['position'] === null) {
            return false;
        }
        $allowed_values = ["Top Left", "Top Center", "Top Right", "Middle Left", "Middle Center", "Middle Right", "Bottom Left", "Bottom Center", "Bottom Right", "Absolute", "Random"];
        if (!in_array($this->container['position'], $allowed_values)) {
            return false;
        }
        if ($this->container['width'] === null) {
            return false;
        }
        if ($this->container['height'] === null) {
            return false;
        }
        $allowed_values = ["Background", "Foreground"];
        if (!in_array($this->container['layer'], $allowed_values)) {
            return false;
        }
        $allowed_values = ["Portrait", "Landscape", "Both"];
        if (!in_array($this->container['page_orientation'], $allowed_values)) {
            return false;
        }
        $allowed_values = ["false", "true"];
        if (!in_array($this->container['print_only'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets source_file_name
     * @return string
     */
    public function getSourceFileName()
    {
        return $this->container['source_file_name'];
    }

    /**
     * Sets source_file_name
     * @param string $source_file_name Name of the source file including extension
     * @return $this
     */
    public function setSourceFileName($source_file_name)
    {
        $this->container['source_file_name'] = $source_file_name;

        return $this;
    }

    /**
     * Gets use_async_pattern
     * @return bool
     */
    public function getUseAsyncPattern()
    {
        return $this->container['use_async_pattern'];
    }

    /**
     * Sets use_async_pattern
     * @param bool $use_async_pattern Use async behaviour for API request
     * @return $this
     */
    public function setUseAsyncPattern($use_async_pattern)
    {
        $this->container['use_async_pattern'] = $use_async_pattern;

        return $this;
    }

    /**
     * Gets source_file_content
     * @return string
     */
    public function getSourceFileContent()
    {
        return $this->container['source_file_content'];
    }

    /**
     * Sets source_file_content
     * @param string $source_file_content Content of the file to watermark
     * @return $this
     */
    public function setSourceFileContent($source_file_content)
    {
        $this->container['source_file_content'] = $source_file_content;

        return $this;
    }

    /**
     * Gets content
     * @return string
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     * @param string $content Data to embed in the Linear Barcode
     * @return $this
     */
    public function setContent($content)
    {
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets sharepoint_file
     * @return \MuhimbiPDFOnline\Client\Model\SharepointFile
     */
    public function getSharepointFile()
    {
        return $this->container['sharepoint_file'];
    }

    /**
     * Sets sharepoint_file
     * @param \MuhimbiPDFOnline\Client\Model\SharepointFile $sharepoint_file
     * @return $this
     */
    public function setSharepointFile($sharepoint_file)
    {
        $this->container['sharepoint_file'] = $sharepoint_file;

        return $this;
    }

    /**
     * Gets barcode_type
     * @return string
     */
    public function getBarcodeType()
    {
        return $this->container['barcode_type'];
    }

    /**
     * Sets barcode_type
     * @param string $barcode_type The type of the barcode
     * @return $this
     */
    public function setBarcodeType($barcode_type)
    {
        $allowed_values = array('Codabar', 'Code11', 'Code32', 'Code39', 'Code39Extended', 'Code93', 'Code93Extended', 'Code128', 'Code128A', 'Code128B', 'Code128C', 'GS1Code128', 'UPC_A');
        if ((!in_array($barcode_type, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'barcode_type', must be one of 'Codabar', 'Code11', 'Code32', 'Code39', 'Code39Extended', 'Code93', 'Code93Extended', 'Code128', 'Code128A', 'Code128B', 'Code128C', 'GS1Code128', 'UPC_A'");
        }
        $this->container['barcode_type'] = $barcode_type;

        return $this;
    }

    /**
     * Gets omit_start_stop_symbols
     * @return string
     */
    public function getOmitStartStopSymbols()
    {
        return $this->container['omit_start_stop_symbols'];
    }

    /**
     * Sets omit_start_stop_symbols
     * @param string $omit_start_stop_symbols Flag indicating if start and stop symbols have to be encoded into the barcode or not
     * @return $this
     */
    public function setOmitStartStopSymbols($omit_start_stop_symbols)
    {
        $allowed_values = array('true', 'false');
        if (!is_null($omit_start_stop_symbols) && (!in_array($omit_start_stop_symbols, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'omit_start_stop_symbols', must be one of 'true', 'false'");
        }
        $this->container['omit_start_stop_symbols'] = $omit_start_stop_symbols;

        return $this;
    }

    /**
     * Gets disable_checkdigit
     * @return string
     */
    public function getDisableCheckdigit()
    {
        return $this->container['disable_checkdigit'];
    }

    /**
     * Sets disable_checkdigit
     * @param string $disable_checkdigit Flag indicating if the check digit has to be calculated or not
     * @return $this
     */
    public function setDisableCheckdigit($disable_checkdigit)
    {
        $allowed_values = array('true', 'false');
        if ((!in_array($disable_checkdigit, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'disable_checkdigit', must be one of 'true', 'false'");
        }
        $this->container['disable_checkdigit'] = $disable_checkdigit;

        return $this;
    }

    /**
     * Gets show_checkdigit
     * @return string
     */
    public function getShowCheckdigit()
    {
        return $this->container['show_checkdigit'];
    }

    /**
     * Sets show_checkdigit
     * @param string $show_checkdigit Flag indicating if the check digit should be displayed in the barcode label or not
     * @return $this
     */
    public function setShowCheckdigit($show_checkdigit)
    {
        $allowed_values = array('true', 'false');
        if ((!in_array($show_checkdigit, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'show_checkdigit', must be one of 'true', 'false'");
        }
        $this->container['show_checkdigit'] = $show_checkdigit;

        return $this;
    }

    /**
     * Gets margin
     * @return string
     */
    public function getMargin()
    {
        return $this->container['margin'];
    }

    /**
     * Sets margin
     * @param string $margin Margin around the barcode
     * @return $this
     */
    public function setMargin($margin)
    {
        $this->container['margin'] = $margin;

        return $this;
    }

    /**
     * Gets font_family_name
     * @return string
     */
    public function getFontFamilyName()
    {
        return $this->container['font_family_name'];
    }

    /**
     * Sets font_family_name
     * @param string $font_family_name Name of the font, e.g. Arial, Times New Roman, Calibri
     * @return $this
     */
    public function setFontFamilyName($font_family_name)
    {
        $this->container['font_family_name'] = $font_family_name;

        return $this;
    }

    /**
     * Gets font_size
     * @return string
     */
    public function getFontSize()
    {
        return $this->container['font_size'];
    }

    /**
     * Sets font_size
     * @param string $font_size Size of the font in Pt
     * @return $this
     */
    public function setFontSize($font_size)
    {
        $this->container['font_size'] = $font_size;

        return $this;
    }

    /**
     * Gets font_style
     * @return string
     */
    public function getFontStyle()
    {
        return $this->container['font_style'];
    }

    /**
     * Sets font_style
     * @param string $font_style One or more styles, e.g. bold|italic|underline|strikeout
     * @return $this
     */
    public function setFontStyle($font_style)
    {
        $this->container['font_style'] = $font_style;

        return $this;
    }

    /**
     * Gets label_placement
     * @return string
     */
    public function getLabelPlacement()
    {
        return $this->container['label_placement'];
    }

    /**
     * Sets label_placement
     * @param string $label_placement Placement of the barcode label
     * @return $this
     */
    public function setLabelPlacement($label_placement)
    {
        $allowed_values = array('Top Left', 'Top Center', 'Top Right', 'None', 'Bottom Left', 'Bottom Center', 'Bottom Right');
        if (!is_null($label_placement) && (!in_array($label_placement, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'label_placement', must be one of 'Top Left', 'Top Center', 'Top Right', 'None', 'Bottom Left', 'Bottom Center', 'Bottom Right'");
        }
        $this->container['label_placement'] = $label_placement;

        return $this;
    }

    /**
     * Gets position
     * @return string
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     * @param string $position Watermark position on the page
     * @return $this
     */
    public function setPosition($position)
    {
        $allowed_values = array('Top Left', 'Top Center', 'Top Right', 'Middle Left', 'Middle Center', 'Middle Right', 'Bottom Left', 'Bottom Center', 'Bottom Right', 'Absolute', 'Random');
        if ((!in_array($position, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'position', must be one of 'Top Left', 'Top Center', 'Top Right', 'Middle Left', 'Middle Center', 'Middle Right', 'Bottom Left', 'Bottom Center', 'Bottom Right', 'Absolute', 'Random'");
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets width
     * @return string
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     * @param string $width Width of the watermark (in Pts, 1/72 of an inch)
     * @return $this
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     * @return string
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     * @param string $height Height of the watermark (in Pts, 1/72 of an inch)
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets x
     * @return string
     */
    public function getX()
    {
        return $this->container['x'];
    }

    /**
     * Sets x
     * @param string $x X Coordinate when 'Position' is set to 'Absolute' (in Pts, 1/72 of an inch)
     * @return $this
     */
    public function setX($x)
    {
        $this->container['x'] = $x;

        return $this;
    }

    /**
     * Gets y
     * @return string
     */
    public function getY()
    {
        return $this->container['y'];
    }

    /**
     * Sets y
     * @param string $y Y Coordinate when 'Position' is set to 'Absolute' (in Pts, 1/72 of an inch)
     * @return $this
     */
    public function setY($y)
    {
        $this->container['y'] = $y;

        return $this;
    }

    /**
     * Gets layer
     * @return string
     */
    public function getLayer()
    {
        return $this->container['layer'];
    }

    /**
     * Sets layer
     * @param string $layer Watermark layer
     * @return $this
     */
    public function setLayer($layer)
    {
        $allowed_values = array('Background', 'Foreground');
        if (!is_null($layer) && (!in_array($layer, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'layer', must be one of 'Background', 'Foreground'");
        }
        $this->container['layer'] = $layer;

        return $this;
    }

    /**
     * Gets rotation
     * @return string
     */
    public function getRotation()
    {
        return $this->container['rotation'];
    }

    /**
     * Sets rotation
     * @param string $rotation Angle of rotation
     * @return $this
     */
    public function setRotation($rotation)
    {
        $this->container['rotation'] = $rotation;

        return $this;
    }

    /**
     * Gets opacity
     * @return string
     */
    public function getOpacity()
    {
        return $this->container['opacity'];
    }

    /**
     * Sets opacity
     * @param string $opacity Opacity in % (100 is fully visible and 1 is barely visible)
     * @return $this
     */
    public function setOpacity($opacity)
    {
        $this->container['opacity'] = $opacity;

        return $this;
    }

    /**
     * Gets fill_color
     * @return string
     */
    public function getFillColor()
    {
        return $this->container['fill_color'];
    }

    /**
     * Sets fill_color
     * @param string $fill_color Color in #RRGGBB notation
     * @return $this
     */
    public function setFillColor($fill_color)
    {
        $this->container['fill_color'] = $fill_color;

        return $this;
    }

    /**
     * Gets line_color
     * @return string
     */
    public function getLineColor()
    {
        return $this->container['line_color'];
    }

    /**
     * Sets line_color
     * @param string $line_color Color in #RRGGBB notation
     * @return $this
     */
    public function setLineColor($line_color)
    {
        $this->container['line_color'] = $line_color;

        return $this;
    }

    /**
     * Gets start_page
     * @return int
     */
    public function getStartPage()
    {
        return $this->container['start_page'];
    }

    /**
     * Sets start_page
     * @param int $start_page Number of the first page the watermark applies to
     * @return $this
     */
    public function setStartPage($start_page)
    {
        $this->container['start_page'] = $start_page;

        return $this;
    }

    /**
     * Gets end_page
     * @return int
     */
    public function getEndPage()
    {
        return $this->container['end_page'];
    }

    /**
     * Sets end_page
     * @param int $end_page Number of the last page the watermark applies to
     * @return $this
     */
    public function setEndPage($end_page)
    {
        $this->container['end_page'] = $end_page;

        return $this;
    }

    /**
     * Gets page_interval
     * @return int
     */
    public function getPageInterval()
    {
        return $this->container['page_interval'];
    }

    /**
     * Sets page_interval
     * @param int $page_interval Which pages to display the watermark on (1=every page, 2=every other, etc)
     * @return $this
     */
    public function setPageInterval($page_interval)
    {
        $this->container['page_interval'] = $page_interval;

        return $this;
    }

    /**
     * Gets page_orientation
     * @return string
     */
    public function getPageOrientation()
    {
        return $this->container['page_orientation'];
    }

    /**
     * Sets page_orientation
     * @param string $page_orientation Orientation of pages the watermark applies to.
     * @return $this
     */
    public function setPageOrientation($page_orientation)
    {
        $allowed_values = array('Portrait', 'Landscape', 'Both');
        if (!is_null($page_orientation) && (!in_array($page_orientation, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'page_orientation', must be one of 'Portrait', 'Landscape', 'Both'");
        }
        $this->container['page_orientation'] = $page_orientation;

        return $this;
    }

    /**
     * Gets print_only
     * @return string
     */
    public function getPrintOnly()
    {
        return $this->container['print_only'];
    }

    /**
     * Sets print_only
     * @param string $print_only Tells if the watermark is only visible when the document is printed
     * @return $this
     */
    public function setPrintOnly($print_only)
    {
        $allowed_values = array('false', 'true');
        if (!is_null($print_only) && (!in_array($print_only, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'print_only', must be one of 'false', 'true'");
        }
        $this->container['print_only'] = $print_only;

        return $this;
    }

    /**
     * Gets start_section
     * @return int
     */
    public function getStartSection()
    {
        return $this->container['start_section'];
    }

    /**
     * Sets start_section
     * @param int $start_section The first section in a Word or Excel document the watermark is visible
     * @return $this
     */
    public function setStartSection($start_section)
    {
        $this->container['start_section'] = $start_section;

        return $this;
    }

    /**
     * Gets end_section
     * @return int
     */
    public function getEndSection()
    {
        return $this->container['end_section'];
    }

    /**
     * Sets end_section
     * @param int $end_section The last section in a Word or Excel document the watermark is visible
     * @return $this
     */
    public function setEndSection($end_section)
    {
        $this->container['end_section'] = $end_section;

        return $this;
    }

    /**
     * Gets page_type
     * @return string
     */
    public function getPageType()
    {
        return $this->container['page_type'];
    }

    /**
     * Sets page_type
     * @param string $page_type One or more page types for Word and Excel documents, eg. default|first|even
     * @return $this
     */
    public function setPageType($page_type)
    {
        $this->container['page_type'] = $page_type;

        return $this;
    }

    /**
     * Gets fail_on_error
     * @return bool
     */
    public function getFailOnError()
    {
        return $this->container['fail_on_error'];
    }

    /**
     * Sets fail_on_error
     * @param bool $fail_on_error Fail on error
     * @return $this
     */
    public function setFailOnError($fail_on_error)
    {
        $this->container['fail_on_error'] = $fail_on_error;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\MuhimbiPDFOnline\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\MuhimbiPDFOnline\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


