/*
 * Muhimbi PDF
 *
 * Convert, Merge, Watermark, Secure and OCR files.
 *
 * The version of the OpenAPI document: 9.16
 * Contact: support@muhimbi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Muhimbi.PDF.Online.Client.Client;
using Muhimbi.PDF.Online.Client.Model;

namespace Muhimbi.PDF.Online.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMergeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Merge documents
        /// </summary>
        /// <remarks>
        /// Merge multiple files into a single PDF.
        /// </remarks>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OperationResponse</returns>
        OperationResponse MergeToPdf(MergeToPdfData inputData, int operationIndex = 0);

        /// <summary>
        /// Merge documents
        /// </summary>
        /// <remarks>
        /// Merge multiple files into a single PDF.
        /// </remarks>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OperationResponse</returns>
        ApiResponse<OperationResponse> MergeToPdfWithHttpInfo(MergeToPdfData inputData, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMergeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Merge documents
        /// </summary>
        /// <remarks>
        /// Merge multiple files into a single PDF.
        /// </remarks>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OperationResponse</returns>
        System.Threading.Tasks.Task<OperationResponse> MergeToPdfAsync(MergeToPdfData inputData, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Merge documents
        /// </summary>
        /// <remarks>
        /// Merge multiple files into a single PDF.
        /// </remarks>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OperationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OperationResponse>> MergeToPdfWithHttpInfoAsync(MergeToPdfData inputData, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMergeApi : IMergeApiSync, IMergeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MergeApi : IMergeApi
    {
        private Muhimbi.PDF.Online.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MergeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MergeApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MergeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MergeApi(string basePath)
        {
            this.Configuration = Muhimbi.PDF.Online.Client.Client.Configuration.MergeConfigurations(
                Muhimbi.PDF.Online.Client.Client.GlobalConfiguration.Instance,
                new Muhimbi.PDF.Online.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Muhimbi.PDF.Online.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Muhimbi.PDF.Online.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Muhimbi.PDF.Online.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MergeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MergeApi(Muhimbi.PDF.Online.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Muhimbi.PDF.Online.Client.Client.Configuration.MergeConfigurations(
                Muhimbi.PDF.Online.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Muhimbi.PDF.Online.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Muhimbi.PDF.Online.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Muhimbi.PDF.Online.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MergeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MergeApi(Muhimbi.PDF.Online.Client.Client.ISynchronousClient client, Muhimbi.PDF.Online.Client.Client.IAsynchronousClient asyncClient, Muhimbi.PDF.Online.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Muhimbi.PDF.Online.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Muhimbi.PDF.Online.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Muhimbi.PDF.Online.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Muhimbi.PDF.Online.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Muhimbi.PDF.Online.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Merge documents Merge multiple files into a single PDF.
        /// </summary>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OperationResponse</returns>
        public OperationResponse MergeToPdf(MergeToPdfData inputData, int operationIndex = 0)
        {
            Muhimbi.PDF.Online.Client.Client.ApiResponse<OperationResponse> localVarResponse = MergeToPdfWithHttpInfo(inputData);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merge documents Merge multiple files into a single PDF.
        /// </summary>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OperationResponse</returns>
        public Muhimbi.PDF.Online.Client.Client.ApiResponse<OperationResponse> MergeToPdfWithHttpInfo(MergeToPdfData inputData, int operationIndex = 0)
        {
            // verify the required parameter 'inputData' is set
            if (inputData == null)
            {
                throw new Muhimbi.PDF.Online.Client.Client.ApiException(400, "Missing required parameter 'inputData' when calling MergeApi->MergeToPdf");
            }

            Muhimbi.PDF.Online.Client.Client.RequestOptions localVarRequestOptions = new Muhimbi.PDF.Online.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Muhimbi.PDF.Online.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Muhimbi.PDF.Online.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = inputData;

            localVarRequestOptions.Operation = "MergeApi.MergeToPdf";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }
            // authentication (oauth2_auth) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OperationResponse>("/v1/operations/merge_to_pdf", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MergeToPdf", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Merge documents Merge multiple files into a single PDF.
        /// </summary>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OperationResponse</returns>
        public async System.Threading.Tasks.Task<OperationResponse> MergeToPdfAsync(MergeToPdfData inputData, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Muhimbi.PDF.Online.Client.Client.ApiResponse<OperationResponse> localVarResponse = await MergeToPdfWithHttpInfoAsync(inputData, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merge documents Merge multiple files into a single PDF.
        /// </summary>
        /// <exception cref="Muhimbi.PDF.Online.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputData"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OperationResponse)</returns>
        public async System.Threading.Tasks.Task<Muhimbi.PDF.Online.Client.Client.ApiResponse<OperationResponse>> MergeToPdfWithHttpInfoAsync(MergeToPdfData inputData, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'inputData' is set
            if (inputData == null)
            {
                throw new Muhimbi.PDF.Online.Client.Client.ApiException(400, "Missing required parameter 'inputData' when calling MergeApi->MergeToPdf");
            }


            Muhimbi.PDF.Online.Client.Client.RequestOptions localVarRequestOptions = new Muhimbi.PDF.Online.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Muhimbi.PDF.Online.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Muhimbi.PDF.Online.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = inputData;

            localVarRequestOptions.Operation = "MergeApi.MergeToPdf";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api_key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api_key", this.Configuration.GetApiKeyWithPrefix("api_key"));
            }
            // authentication (oauth2_auth) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<OperationResponse>("/v1/operations/merge_to_pdf", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MergeToPdf", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
